import Head from 'next/head'
import styles from './Mainlayout.module.css'
import { Navbar } from '../Navbar'

export const MainLayout = ({ children }:any) => {
    return (
        <>
          <Head>
            <title>Home - Miguel</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar/>
          <main className={`${styles.main}`}>
            {children}
          </main>
        </>
      )
}
